---
- hosts: localhost
  connection: local

  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - vim

    - name: Install apps with brew-cask
      homebrew_cask: name={{ item }} state=present
      with_items:
      #      - google-chrome
      #      - firefox
      #      - sublime-text
      #      - transmit
            - atom
            - iterm2
            - aerial
