---
- hosts: localhost
  connection: local

  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - vim
        - bash
        - bash-completion
        - ant
        - maven
        - pstree
        - oath-toolkit
        - gs
        - watch
        - graphviz
        - docker
        - boot2docker
        - coreutils
        - tree
        - iftop
        - pandoc    # Used to build the documentation
        - hub       # Github extension
        - qemu
        - rbenv
        - ruby-build
        - ssh-copy-id
        - dos2unix

    - name: Install apps with brew-cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - google-chrome
        - firefox
        # File management
        - transmit
        - path-finder
        - dropbox
        - beyond-compare
        - gemini
        # Coding
        - iterm2
        - sourcetree
        # Text editors
        - sublime-text
        - atom
        # Virtualisation
        - vagrant
        - virtualbox
        # Task management
        - things
        # Screen saver
        - aerial
        # Other
        - evernote
        - balsamiq-mockups
        - jd-gui
        # Media
        - spotify
        - vlc
        # Communication
        - limechat
        - skype
        - telegram
        # Security
        - 1password
        - wireshark
        - owasp-zap
        - nmap
        # System
        - appcleaner
        - cleanmymac
        - alfred
        - onyx
        - spectacle     # windows management
        - xquartz
        # Draw
        - inkscape
        - gimp
        - dia
