---
- hosts: localhost
  connection: local

  tasks:
    - name: Install libraries with homebrew (brew)
      homebrew: name={{ item }} state=present
      with_items: '{{homebrew_libraries}}'

    - name: Install applications with brew-cask
      homebrew_cask: name={{ item }} state=present
      with_items: '{{homebrew_cask_applications}}'

    # Need to wait for a better brew cask version for improving this
    - name: Force installation
      sudo: true
      shell: brew cask install --force {{ item }}
      with_items: '{{homebrew_cask_applications}}'

    - name: Install gems
      gem: name={{item.name}} pre_release={{item.pre}} state=present
      with_items: '{{gems}}'

    - name: Remove icons from Dock
      shell: dockutil --remove '{{ item }}'
      ignore_errors: true
      with_items: '{{dockitems_to_remove}}'

    - name: Remove icons from Dock
      shell: dockutil --remove '{{ item.name }}'
      ignore_errors: true
      with_items: '{{dockitems_to_persist}}'

    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: '{{dockitems_to_persist}}'

    - name: Fix order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
      with_items: '{{dockitems_to_persist}}'
