---
- hosts: localhost
  connection: local
  become_method: sudo

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - group_vars/brew_var.yml
        - group_vars/dock_var.yml
        - group_vars/gem_var.yml
        - group_vars/mas_var.yml

  roles:
    - role: Comcast.sdkman
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.5.hs-adpt }
      sdkman_defaults:
        java: 11.0.5.hs-adpt
      when: configure_sdkman
  
  tasks:
    - import_tasks: tasks/osx.yml
      when: configure_osx

    - import_tasks: tasks/brew.yml
      when: configure_brew

    - import_tasks: tasks/gem.yml
      when: configure_gem

    - import_tasks: tasks/mas.yml
      when: configure_mas

    - import_tasks: tasks/dock.yml
      when: configure_dock
