---
- name: <BREW> Install taps with homebrew
  homebrew_tap: name={{ item }} state=present
  with_items: '{{brew_taps}}'

- name: <BREW> Install casks with homebrew
  homebrew_cask: name={{ item }} state=present install_options=force
  with_items: '{{brew_casks}}'

- name: <BREW> Install apps with homebrew
  homebrew: name={{ item }} state=present
  with_items: '{{brew_apps}}'
