---
- name: <BREW> Install taps with homebrew
  homebrew_tap: name={{ brew_taps }} state=present

- name: <BREW> Install casks with homebrew
  homebrew_cask: name={{ brew_casks }} state=present

# NOTE: Change to the following to force the install
#  homebrew_cask: name={{ brew_casks }} state=present install_options=force

- name: <BREW> Install apps with homebrew
  homebrew: name={{ brew_apps }} state=present