---

- name: <DOCK> Ensure 'dockutil' is installed
  homebrew: name=dockutil state=present

- name: <DOCK> Remove icons from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: '{{dockitems_to_remove}}'

- name: <DOCK> Remove icons from Dock
  shell: dockutil --remove '{{ item.name }}'
  ignore_errors: true
  with_items: '{{dockitems_to_persist}}'

- name: <DOCK> Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: '{{dockitems_to_persist}}'

- name: <DOCK> Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: '{{dockitems_to_persist}}'
