---

- name: <MAS> Ensure RUBY is installed
  homebrew: name={{item}} state=present
  with_items:
    - ruby
    - ruby-build

- name: <GEM> Install ruby gems
  gem: name={{item.name}} pre_release={{item.pre}} version={{item.version}} state=present
  with_items: '{{gems}}'
