---

- name: <GEM> Ensure RUBY is installed
  homebrew: name={{item}} state=present
  with_items:
    - ruby
    - ruby-build

- name: <GEM> Install ruby gems with version
  gem: name={{item.name}} pre_release={{item.pre}} state=present
  with_items: '{{gems_with_version}}'

- name: <GEM> Install ruby gems
  gem: name={{item.name}} state=present
  with_items: '{{gems}}'
