---

# Disable Google Chrome swipe behaviour
# http://osxdaily.com/2015/05/09/disable-swipe-navigation-google-chrome-mac/
# defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE
- name: <OSX> Disable chrome swipe navigation
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false
    state: present

- name: Disable the Screensaver
  shell: defaults write com.apple.screensaver idleTime 0

- name: Show File Extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Show the Status Bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: Show the Path Bar in Finder
  shell: defaults write com.apple.finder ShowPathbar -bool true

- name: Restart Finder
  shell: killall Finder
