---

# Disable Google Chrome swipe behaviour
# http://osxdaily.com/2015/05/09/disable-swipe-navigation-google-chrome-mac/
# defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE
- name: <OSX> Disable chrome swipe navigation
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false
    state: present

- name: Disable the Screensaver
  shell: defaults write com.apple.screensaver idleTime 0

- name: Show File Extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Show the Status Bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: Show the Path Bar in Finder
  shell: defaults write com.apple.finder ShowPathbar -bool true

- name: Restart Finder
  shell: killall Finder

# Taken from https://github.com/superlumic/ansible-role-computername
- name: Set computername
  shell: scutil --set ComputerName {{ computername }}
  become: yes
  when: ansible_hostname != computername

- name: Set hostname
  shell: scutil --set HostName {{ computername }}
  become: yes
  when: ansible_hostname != computername

- name: Set localhostname
  shell: scutil --set LocalHostName {{ computername }}
  become: yes
  when: ansible_hostname != computername

- name: Set the netbios name
  become: yes
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ computername }}"
    state: present
